---
- name: "Laboratorio de Facts"
  hosts: nodo01
 
  tasks:
  - name: "Mirar HORA ANTES"
    setup:
      filter: ansible_*
    register: salida_antes
  - name: "Poner timezone en Europe/Moscow"
    timezone:
      name: Europe/Moscow
  - name: "Mirar HORA DESPUES"
    setup:
      filter: ansible_*
    register: salida_despues
  - name: "imprimir salida_despues"
    debug:
      msg: "La salida es: {{ salida_despues.ansible_facts.ansible_hostname }}"

  - name: "Crear fichero"
    file:
        path: "{{ salida_antes.ansible_facts.ansible_hostname }}"
        state: touch
        mode: 0655
  - name: "Anadir datos al fichero"
    lineinfile:
      path: "{{ salida_antes.ansible_facts.ansible_hostname }}"
      line: |
        - La zona horaria antes del cambio es zona_horaria_antes y la hora era {{ salida_antes.ansible_facts.ansible_data_time }}
        - La zona horaria despues del cambio es zona_horaria_despues y la hora era {{ salida_despues.ansible_facts.ansible_data_time }}
      create: yes
  - name: "Volver a dejar en Europe/Madrid"
    timezone:
      name: Europe/Madrid

...